### ISSUE TITLE
Web support with signInWithPhoneNumber?

### ISSUE THREAD

**Issue by giorgio79** [rithik-dev/firebase_phone_auth_handler#1]
According to the FlutterFire package, for web we should use the signInWithPhoneNumber method. Any plans for that? https://firebase.flutter.dev/docs/auth/phone/

**Comment by rithik-dev** [comment]
Yes, I am working on integrating it for the web.

**Comment by rithik-dev** [comment]
Hi @giorgio79 , the fix is live. Try using the latest version and it works on the web. Thanks for reporting this issue.
