### ISSUE TITLE
calling api inside onLoginSuccess  callback

### ISSUE THREAD

**Issue by abdullahehab** [rithik-dev/firebase_phone_auth_handler#10]
when calling api inside onLoginSuccess the application re-send verification code 

Uploading Screen Recording 2022-07-28 at 12.26.15 PM.mov…

<img width="783" alt="Screen Shot 2022-07-28 at 12 27 04 PM" src="https://user-images.githubusercontent.com/30800958/181484030-cee9dedf-587a-49c8-896c-a1ecf6ad0e02.png">

**Comment by rithik-dev** [comment]
Hey @abdullahehab, can you share the full screen code? This usually does not happen, the code is sent only once.

Or if you could upload a video demonstrating the issue...

**Comment by abdullahehab** [comment]
https://user-images.githubusercontent.com/30800958/181862496-6a1de5a5-28ea-432e-8b21-12feb5096611.mov

**Comment by abdullahehab** [comment]
import 'dart:developer';

import 'package:another_flushbar/flushbar_helper.dart';
import 'package:firebase_phone_auth_handler/firebase_phone_auth_handler.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pin_code_fields/pin_code_fields.dart';
import 'package:provider/provider.dart';
import 'package:waiter_app/stores/user/user_store.dart';

import '../../constants/colors.dart';
import '../../constants/dimens.dart';
import '../../di/components/service_locator.dart';
import '../../di/extensions/extensions.dart';
import '../../stores/language/language_store.dart';
import '../../utils/routes/routes.dart';
import '../../widgets/rounded_button_widget.dart';

class VerifyLoginScreen extends StatefulWidget {
  @override
  _VerifyLoginScreenState createState() => _VerifyLoginScreenState();
}

class _VerifyLoginScreenState extends State<VerifyLoginScreen> {
  //stores:---------------------------------------------------------------------
  final _store = getIt<UserStore>();
  late LanguageStore _languageStore;

  late final ScrollController scrollController;
  TextEditingController? _otpController = TextEditingController();

  @override
  void initState() {
    scrollController = ScrollController();
    super.initState();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    // initializing stores
    _languageStore = Provider.of<LanguageStore>(context);
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FirebasePhoneAuthHandler(
      phoneNumber: '+2${_store.phone}',
      signOutOnSuccessfulVerification: false,
      autoRetrievalTimeOutDuration: const Duration(seconds: 30),
      otpExpirationDuration: const Duration(seconds: 60),
      onCodeSent: () {},
      onLoginSuccess: (userCredential, autoVerified) async {
        userCredential.user?.getIdToken().then((token) async {
          // SharedPreferences.getInstance().then((prefs) {
          //   prefs.setBool(Preferences.is_logged_in, true);
          //   prefs.setString(Preferences.firebase_token, token);
          // });

          _store.getAppData(token).then((value) {
            if (_store.isLoggedIn) {
              Future.delayed(const Duration(seconds: 1), () {
                Navigator.of(context).pushNamedAndRemoveUntil(
                    Routes.bottomNavigationBar,
                    (Route<dynamic> route) => false);
              });
            }
          });
        });
      },
      onLoginFailed: (authException) {
        log(_store.phone);
        _showErrorMessage('something_went_wrong'.tr(context));
        log(authException.message.toString());
        // handle error further if needed
      },
      builder: (context, controller) {
        return Scaffold(
          backgroundColor: AppColors.appBarBackgroundColor,
          appBar: _buildAppBar(),
          body: controller.isSendingCode
              ? Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    const SizedBox(height: 50),
                    Center(
                      child: Text(
                        'sending_otp'.tr(context),
                        style: const TextStyle(fontSize: 25),
                      ),
                    ),
                  ],
                )
              : _buildBody(controller),
        );
      },
    );
  }

  // app bar methods:-----------------------------------------------------------
  PreferredSizeWidget _buildAppBar() {
    return AppBar(
      backgroundColor: AppColors.appBarBackgroundColor,
      leading: GestureDetector(
          onTap: () => Navigator.pop(context),
          child: const Icon(Icons.arrow_back, color: AppColors.blackColor)),
      actions: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Row(
            children: [
              const Icon(Icons.help_outline, color: AppColors.blackColor),
              const SizedBox(width: 6),
              Text(
                'help'.tr(context),
                style: const TextStyle(color: AppColors.blackColor),
              )
            ],
          ),
        ),
      ],
      bottom: PreferredSize(
          preferredSize: const Size.fromHeight(10.0),
          child: Padding(
            padding: const EdgeInsets.symmetric(
                horizontal: Dimens.horizontal_padding),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Text(
                  'enter_confirmation_code'.tr(context),
                  style: const TextStyle(fontWeight: FontWeight.bold),
                ),
              ],
            ),
          )),
    );
  }

  // body methods:--------------------------------------------------------------
  Widget _buildBody(FirebasePhoneAuthController controller) {
    var size = MediaQuery.of(context).size;

    bool isAr = _languageStore.isAr;

    return Column(
      children: [
        const SizedBox(height: 30),
        Expanded(
          child: SingleChildScrollView(
            physics: const NeverScrollableScrollPhysics(),
            child: Container(
              height: size.height,
              width: size.width,
              decoration: const BoxDecoration(
                  color: AppColors.loginBackgroundColor,
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(20.0),
                    topRight: Radius.circular(20.0),
                  )),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Row(
                    children: [
                      Padding(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 15, vertical: 20),
                          child: RichText(
                            text: TextSpan(
                              text:
                                  '${'code_has_been_sent'.tr(context)} \n ${!isAr ? '+' : ''}2${_store.phone} ${isAr ? '+' : ''} ',
                              style:
                                  const TextStyle(color: AppColors.blackColor),
                              children: <TextSpan>[
                                TextSpan(
                                  text: 'change_number'.tr(context),
                                  style: const TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color: AppColors.buttonColor),
                                  recognizer: TapGestureRecognizer()
                                    ..onTap = () {
                                      Navigator.pop(context);
                                    },
                                ),
                              ],
                            ),
                          )),
                    ],
                  ),
                  _buildOtp(controller),
                  _buildReSendCodeWidget(controller)
                ],
              ),
            ),
          ),
        ),
        _buildVerifyButton(controller)
      ],
    );
  }

  Widget _buildOtp(FirebasePhoneAuthController controller) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: PinCodeTextField(
          hintCharacter: '-',
          keyboardType: TextInputType.number,
          controller: _otpController,
          inputFormatters: [FilteringTextInputFormatter.digitsOnly],
          pinTheme: PinTheme(
              shape: PinCodeFieldShape.box,
              borderRadius: BorderRadius.circular(Dimens.borderRadius + 3),
              fieldHeight: 50,
              fieldWidth: 55,
              borderWidth: 1.5,
              activeFillColor: Colors.white,
              activeColor: AppColors.borderColor,
              inactiveColor: AppColors.borderColor,
              inactiveFillColor: AppColors.borderColor,
              disabledColor: AppColors.borderColor,
              errorBorderColor: Colors.red,
              selectedColor: AppColors.borderColor,
              selectedFillColor: AppColors.borderColor),
          length: 6,
          onSubmitted: (enteredOtp) async {
            final isValidOtp = await controller.verifyOtp(enteredOtp);
            // Incorrect OTP
            if (!isValidOtp) {
              _showErrorMessage(
                'the_entered_otp_is_invalid'.tr(context),
              );
            }
          },
          appContext: context,
          onChanged: (String value) {},
        ),
      ),
    );
  }

  Widget _buildReSendCodeWidget(FirebasePhoneAuthController controller) {
    return controller.codeSent
        ? Column(
            children: [
              const SizedBox(height: 20),
              TextButton(
                onPressed: controller.isOtpExpired
                    ? () async {
                        log('Resend OTP');
                        _otpController = null;
                        await controller.sendOTP();
                      }
                    : null,
                child: Text(
                  're_send_request'.tr(context),
                  style: const TextStyle(
                      fontWeight: FontWeight.bold,
                      color: Colors.grey,
                      fontSize: 20),
                ),
              ),
              const SizedBox(height: 20),
              if (!controller.isOtpExpired)
                TextButton(
                  onPressed: () {},
                  child: Text(
                    '${'re_send_message'.tr(context)}( ${controller.otpExpirationTimeLeft.inSeconds} )',
                    style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        color: AppColors.blackColor),
                  ),
                ),
            ],
          )
        : const SizedBox();
  }

  Widget _buildVerifyButton(FirebasePhoneAuthController controller) {
    var size = MediaQuery.of(context).size;
    return Center(
      child: Container(
        width: size.width,
        color: AppColors.loginBackgroundColor,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 25),
          child: RoundedButtonWidget(
            buttonText: 'verify_login_btn_sign_in'.tr(context),
            buttonColor: AppColors.buttonColor,
            textColor: Colors.white,
            borderRadius: Dimens.borderRadius + 4,
            width: size.width,
            height: 48,
            onPressed: () async {
              final isValidOtp =
                  await controller.verifyOtp(_otpController!.text);
              // Incorrect OTP
              if (!isValidOtp) {
                'the_entered_otp_is_invalid'.tr(context);
              }
            },
          ),
        ),
      ),
    );
  }

  // General Methods:-----------------------------------------------------------
  _showErrorMessage(String message) {
    Future.delayed(const Duration(milliseconds: 0), () {
      if (message.isNotEmpty) {
        FlushbarHelper.createError(
          message: message,
          title: 'home_tv_error'.tr(context),
          duration: const Duration(seconds: 3),
        ).show(context);
      }
    });

    return const SizedBox.shrink();
  }

  _showDialog<T>({required BuildContext context, required Widget child}) {
    showDialog<T>(
      context: context,
      builder: (BuildContext context) => child,
    ).then<void>((T? value) {
      // The value passed to Navigator.pop() or null.
    });
  }
}

**Comment by rithik-dev** [comment]
Hey @abdullahehab ,

Can you re-check your ```Routes.bottomNavigatorBar``` route, becuse the OTP screen reappears after that screen is pushed

Are you popping the screen using some logic?

I don't think the OTP is being resent, IMO you have some logic in the ```Routes.bottomNavigatorBar``` screen, that is popping the screen, and that probably pushes the OTP screen or something...

**Comment by rithik-dev** [comment]
Hi @abdullahehab, this issue looks inactive. I'm closing this, feel free to open another one.
