### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by VladilenC** [rithik-dev/firebase_phone_auth_handler#12]
Because firebase_phone_auth_handler >=1.0.6 depends on firebase_auth ^3.4.2 and App depends on firebase_auth ^4.0.2, firebase_phone_auth_handler >=1.0.6 is forbidden.
So, because App depends on firebase_phone_auth_handler ^1.0.6, version solving failed.

**Comment by rithik-dev** [comment]
Hey @VladilenC , will push a fix by updating the deps in some time..

**Comment by rithik-dev** [comment]
Hey, @VladilenC , the fix is live. Try using v1.0.7.. I'm closing this PR for now, feel free to re-open or create a new one if you find something else..

Thanks for reporting this issue.

**Comment by VladilenC** [comment]
Thanks
