### ISSUE TITLE
Question - ReAuthentication is it possible?

### ISSUE THREAD

**Issue by rajesh-h** [rithik-dev/firebase_phone_auth_handler#13]
Hi @rithik-dev ,

I am using your package.

My current flow is as below.

User Singin/Signup using his phone number, if he is a new user I present him with the form to fill his personal details else navigate to home page.

As part of personal details I update email as well, so what this does is it send's a Signout signal, which logs out the user from the application, and when he is redirected to home page there is no more active user.

When I searched online it said in such cases we need to ReAuthenticate the user but there is no sample how to do it when it is a phone auth.

Do you have any suggestion?

Thanks

**Comment by rithik-dev** [comment]
Hey, you must have the `signOutOnSuccesfulVerification` flag set as true in the widget. Try making that false, and it should work as expected.

**Comment by rajesh-h** [comment]
Thank you very much for the quick response. I do have that setting as false in the widget.

**Comment by rithik-dev** [comment]
You must be calling the sign out function somewhere, because if the user has just created the account, then there shouldn't be the need to re-authenticate.

**Comment by rajesh-h** [comment]
Even I was under same impression.

Basically 1st user gets created, then next step User profile gets updated. I do understand if the account was created immediately there in no need of re-authentication, but I believe since Email update happens as part of user profile I believe it logs user out.

**Comment by rithik-dev** [comment]
I am not exactly sure what is happening here, because this is not how the package behaves. The package will only sign out the user if the signOut flag is true in the widget.

**Comment by rithik-dev** [comment]
Hi @rajesh-h, this issue looks inactive. I'm closing this, feel free to open another one.
