### ISSUE TITLE
Question - Is there any permission need to be provided so SMS can be read by the Flutter App?

### ISSUE THREAD

**Issue by rajesh-h** [rithik-dev/firebase_phone_auth_handler#14]
I tried running the app on actual mobile device but SMS was not read by the app, I am suspecting I might have to ask user for permission to read sms. Is it something necessary? 
if so, does it need to be part of manifest file?

**Comment by rithik-dev** [comment]
Follow the README carefully, you should not face any issue setting this up. BTW, OTP auto-fetch only works on android.

**Comment by rithik-dev** [comment]
No permission is required though..

**Comment by rithik-dev** [comment]
Don't forget to add you SHA keys in the firebase console

**Comment by rithik-dev** [comment]
Hi @rajesh-h, this issue looks inactive. I'm closing this, feel free to open another one.
