### ISSUE TITLE
Enable Android Device Verification 

### ISSUE THREAD

**Issue by ljsharp** [rithik-dev/firebase_phone_auth_handler#17]
I followed your instructions but Android Device Verification is not found in Google Cloud instead of Google Play Integrity.  What should I do please? Thanks.

**Comment by rithik-dev** [comment]
Hey @ljsharp, the Android Device Verification API is now replaced by the Google Play Integrity API.

Please use this API instead of the device verification one. Will push out an update to the README and fix the docs accordingly.

**Comment by ljsharp** [comment]
Very well noted. Thanks

**Comment by azazadev** [comment]
> 

Thanks @rithik-dev : please keep ticket open until doc update to avoid confusion

**Comment by rithik-dev** [comment]
Sure @azazadev

**Comment by rithik-dev** [comment]
Hey @azazadev, I've released v1.1.0 of the package with updated dependencies, and also updated the README with reference to the `Google Play Integrity API`.
