### ISSUE TITLE
UI glitch in OTP screen

### ISSUE THREAD

**Issue by JaleelNazir** [rithik-dev/firebase_phone_auth_handler#18]
After the OTP is sent, there is a UI glitch in **VerifyPhoneNumberScreen**. Could you please guide me to solve the issue?

Using the example code. 

```
environment:
  sdk: '>=3.1.5 <4.0.0'

firebase_phone_auth_handler: ^1.0.8
```

**Simulator: Pixel 7 API 33**

@rithik-dev

**Comment by JaleelNazir** [comment]
Adding screen recording for reference. Please help.


https://github.com/rithik-dev/firebase_phone_auth_handler/assets/8981430/975a6636-2546-4827-bd15-5eed57adbfb5

**Comment by rithik-dev** [comment]
Hi @JaleelNazir , I just tested the flow on the example app in the repository, and it works as expected. Looks like you missed something while integrating, try referring to the example app here once.

https://github.com/rithik-dev/firebase_phone_auth_handler/tree/master/example

**Comment by JaleelNazir** [comment]
I got the solution. There is an issue with the theme. The problem has been reported earlier in the Flutter repository.

GitHub Issues:
- https://github.com/flutter/flutter/issues/70907
- https://github.com/flutter/flutter/issues/28882

Solution: https://stackoverflow.com/a/72734482/3177007
