### ISSUE TITLE
[question] is it work with huawei phone that not include gms ?

### ISSUE THREAD

**Issue by Joseph-Nathan** [rithik-dev/firebase_phone_auth_handler#2]
i don't know what to do with this devices ??

**Comment by rithik-dev** [comment]
Hey, I am not sure whether it is supported or not. You might want to check whether [firebase_auth](https://pub.dev/packages/firebase_auth) is supported on phones without gms or not. If it's supported, then you won't face any issue using this package on those devices.

**Comment by Joseph-Nathan** [comment]
thanks ,
