### ISSUE TITLE
Can we disable auto login success when receiving SMS code on android devices

### ISSUE THREAD

**Issue by minhkimlong** [rithik-dev/firebase_phone_auth_handler#21]
- I navigate to verify phone screen with my phone number. But after receiving sms code auto login on android devices

**Comment by rithik-slick** [comment]
Hey @minhkimlong , you can use the `autoVerified` boolean in the `onLoginSuccess` callback to check if the otp was auto verified.

**Comment by rithik-dev** [comment]
Hey @minhkimlong, you can use the`autoVerified` boolean in the `onLoginSuccess` callback to check if the otp was auto verified.
