### ISSUE TITLE
Disable Auto Send Code Verification 

### ISSUE THREAD

**Issue by PhanithNoch** [rithik-dev/firebase_phone_auth_handler#3]
I'm making a new project using your package to verification OTP but when I navigate to new screen it auto send. that's not what i want. I want to send code when click button send. help please.

**Comment by rithik-dev** [comment]
Hey, so you would have wrapped the screen containing the Send OTP button, I would recommend not wrapping this screen, but creating a new screen that is pushed when the user clicks the Send OTP button in your UI. The new screen for otp verification will be pushed and code is sent. That screen will contain the ui to enter the code and stuff and then you can call Navigator.pop(context,uid); in the onSuccess callback and use the user's uid. Hope this helps..

**Comment by PhanithNoch** [comment]
Thank you Now it works

**Comment by rithik-dev** [comment]
✔️ You're welcome. If you face any other, feel free to open another issue. I am closing this issue right now.
