### ISSUE TITLE
Why lib does not handle of sending code error

### ISSUE THREAD

**Issue by altayeb3mer** [rithik-dev/firebase_phone_auth_handler#4]
I want to know if some issue with sending code 
to introduce some message to user to tell him to try check if your phone you entered right or something like this

**Comment by rithik-dev** [comment]
The onLoginFailed callback will be triggered in case of any error, and the error itself is passed in the callback, you can handle the error then on your end.

Thanks..

**Comment by rithik-dev** [comment]
I am closing this issue, feel free to open another one if you are facing another issue.

**Comment by altayeb3mer** [comment]
Ok thanks..
