### ISSUE TITLE
login happens after time out

### ISSUE THREAD

**Issue by Safvana-Techvalley** [rithik-dev/firebase_phone_auth_handler#7]
Login also happens after otp time out

**Comment by rithik-dev** [comment]
Hey, the timeoutDuration flag represents the amount of time the device waits to auto-fetch the OTP, after that, the login can still happen, but you'll have to manually enter the OTP in the field.

**Comment by rithik-dev** [comment]
Hey @Safvana-Techvalley, the timeoutDuration flag represents the amount of time the device waits to auto-fetch the OTP, after that, the login can still happen, but you'll have to manually enter the OTP in the field.

**Comment by rithik-dev** [comment]
Hey, @Safvana-Techvalley, in the latest release, I've renamed the timeoutDuration flag to autoRetrievalTimeOutDuration, to make more sense of what it actually is. 

I am closing this issue now, feel free to re-open a new one in case needed.

Thanks for reporting this issue!
