### ISSUE TITLE
linking with a user signed in by username and password

### ISSUE THREAD

**Issue by mufarrah** [rithik-dev/firebase_phone_auth_handler#8]
im implimeting TFA where the user is signed in using email and password, then im sending a tesxt message to the sam user using this package, bu the problem is that this package creates a new reference which is not related to the user reference that is already created using email and password. can you please guid ? thanks

**Comment by rithik-dev** [comment]
Hey @mufarrah, what I can do is expose a boolean something like linkWithExistingUser, that calls the linkWithCredential instead of calling signInWithCredential. I think that'll fix this issue.

**Comment by mufarrah** [comment]
> Hey @mufarrah, what I can do is expose a boolean something like linkWithExistingUser, that calls the linkWithCredential instead of calling signInWithCredential. I think that'll fix this issue.

Could i have a code snippet that explains how to merge this suggested change with the existing code of the package please ??

**Comment by rithik-dev** [comment]
Would have a flag that would call the linkWithCredential method instead of the signInWithCredential.

**Comment by rithik-dev** [comment]
I'll push out a new release today, that'll address this issue.

**Comment by rithik-dev** [comment]
Hi @mufarrah  , the update is live (v1.0.6). Try using the latest version and set the linkWithExistingUser to true, that'll internally call the linkWithCredential method, and work as expected.

Thanks for reporting this issue.

**Comment by mufarrah** [comment]
Hey well done , thanks for the update . I'll try it out , does that works on web as well ?? because im using web. and from which widget i call the linkWithCredential ??

**Comment by rithik-dev** [comment]
The boolean can be passed on the FirebasePhoneAuthHandler widget, and right now it does not work on the web. I was not able to get the authCredential from web sign in, and hence, cannot call the method to link.

On the web, as soon as the OTP is confirmed, the user is signed in automatically.
