### ISSUE TITLE
Question - Can I redirect user based on whether he is NewUser or not

### ISSUE THREAD

**Issue by rajesh-h** [rithik-dev/firebase_phone_auth_handler#9]
Hi Rithik,

Thank you for this package. I am trying to explore more on this.

I am in need of checking if a user is logging in firstTime or he already has an account.

I would like him to fill up his name and other details if he is first time user. So is there a way I can find his status?

I did see this link https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AdditionalUserInfo  but could not apply it on my side.

Your help id much appreciated.

Thanks,
Raj

**Comment by rithik-dev** [comment]
Hey, @rajesh-h, the userCredential object in the onLoginSuccess callback does has a property ```userCredential.additionalUserInfo.isNewUser``` that can be used to check if a user is logging in for the first time.

I tested it, and it works fine.

Try that and let me know if that works for you!

**Comment by rajesh-h** [comment]
Thank you very much @rithik-dev yes it is available.  Once again thank you very much for the package.
